### ISSUE TITLE
$AHKP(example, $arg1) does not run in case the parameter is not provided / null

### ISSUE THREAD

**Issue by quassia** [CrashKoeck/AHKParameters#1]
Step to reproduce:
1. Create the !command1 command which runs $AHKP(example, $arg1)
2. Write at the console just !command1 and notice nothing happens.
This is because Streamlabs does not execute anything if $arg1 is null.  Not exactly a script issue, but I wonder if there is an workaround. 
This is for the case the the script is not always provided with the entire list of parameters.
Thank you.

**Comment by CrashKoeck** [comment]
This is actually a Streamlabs Chatbot limitation. If you have `$arg[1-9]` in the command, it expects there to be that parameter. If there isn’t, I won’t fire the command at all.

A limited way around this would be to use the `$dummyormsg`parameter in Streamlabs Chatbot instead. It’s not perfect, but it would at least work in the example you provided.

Hope this helps!

[image](https://user-images.githubusercontent.com/51434502/83121333-0568ba00-a087-11ea-81a9-adb1b3b48f23.jpeg)
